import { useRef } from "react";

export function useEditorRefs() {
  return {
    assetDropPulseTimerRef: useRef(0),
    audioRef: useRef(null),
    audioSegmentRefs: useRef(new Map()),
    audioUrlRef: useRef(""),
    autoRatioSourceKeyRef: useRef(""),
    avatarMotionCacheRef: useRef({ audioBlob: null, motion: null }),
    avatarMotionWorkerRef: useRef(null),
    avatarRenderWorkerRef: useRef(null),
    avatarTestAudioImportedRef: useRef(false),
    avatarTestImportedRef: useRef(false),
    currentTimeRef: useRef(0),
    draggedAssetIdRef: useRef(""),
    exportStartRef: useRef(0),
    fileInputRef: useRef(null),
    imageUrlRefs: useRef(new Set()),
    musicRef: useRef(null),
    musicUrlRef: useRef(""),
    pointerAssetDragRef: useRef(null),
    previewCanvasRef: useRef(null),
    previewShellRef: useRef(null),
    previewVideoRef: useRef(null),
    projectFileInputRef: useRef(null),
    sourceAudioRef: useRef(null),
    sourceAudioUrlRef: useRef(""),
    suppressAssetClickRef: useRef(""),
    suppressTimelineClipClickRef: useRef(""),
    timelineClipDragRef: useRef(null),
    timelineDurationRef: useRef(0),
    trackScrollRef: useRef(null),
    visionAbortControllerRef: useRef(null),
    visionJobGenerationRef: useRef(0),
    visionObjectUrlsRef: useRef(new Map()),
    visualPlaybackFrameRef: useRef(0),
    visualPlaybackLastUpdateRef: useRef(0),
    visualPlaybackStartedAtRef: useRef(0),
    visualPlaybackStartTimeRef: useRef(0),
    voiceRecorderChunksRef: useRef([]),
    voiceRecorderRef: useRef(null),
    voiceRecorderStartedAtRef: useRef(0),
    voiceRecorderStreamRef: useRef(null),
    voiceRecorderTimerRef: useRef(0),
  };
}
